name: Actions
run-name: Workflow executado por ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      versao:
        type: string
        required: true
        default: "dev"
        description: "Versão da nova release"
      numero_card:
        type: number
        required: true
        description: "Número do card da tarefa desse commit"
      fazer_deploy:
        type: boolean
        required: true
        description: "Irá fazer o deploy ou não"
      ambiente:
        type: choice
        required: true
        description: "Ambiente de deploy"
        options:
          - Desenvolvimento
          - Homologação
          - Produção

env:
  nome_artefato: manipulacao-artefatos

jobs:

  # JOB 1 - Exibição dos inputs do workflow
  valores_input:
    runs-on: ubuntu-latest
    steps:
      - name: Exibindo o contexto de input completo
        run: echo "${{ toJson(inputs) }}"

      - name: Exibindo os valores individualmente
        run: |
          echo "Esses são os valores passados nos inputs:"
          echo "A versão é: ${{ inputs.versao }}"
          echo "O card é: ${{ inputs.numero_card }}"
          echo "Deve fazer deploy: ${{ inputs.fazer_deploy }}"
          echo "O ambiente é: ${{ inputs.ambiente }}"