name: Actions
run-name: Workflow executado por ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      versao:
        type: string
        required: true
        default: "dev"
        description: "Versão da nova release"
      numero_card:
        type: number
        required: true
        description: "Número do card da tarefa desse commit"
      fazer_deploy:
        type: boolean
        required: true
        description: "Irá fazer o deploy ou não"
      ambiente:
        type: choice
        required: true
        description: "Ambiente de deploy"
        options:
          - Desenvolvimento
          - Homologação
          - Produção

env:
  nome_artefato: manipulacao-artefatos

jobs:

  # JOB 1 - Exibição dos inputs do workflow
  valores_input:
    runs-on: ubuntu-latest
    steps:
      - name: Exibindo o contexto de input completo
        run: echo "${{ toJson(inputs) }}"

      - name: Exibindo os valores individualmente
        run: |
          echo "Esses são os valores passados nos inputs:"
          echo "A versão é: ${{ inputs.versao }}"
          echo "O card é: ${{ inputs.numero_card }}"
          echo "Deve fazer deploy: ${{ inputs.fazer_deploy }}"
          echo "O ambiente é: ${{ inputs.ambiente }}"

  # JOB 2 - Cria e envia artefatos
  upload-artfact:
    runs-on: ubuntu-latest
    steps:
      - name: Listagem de arquivos no diretório raiz
        run: ls

      - name: Geração de arquivos
        run: |
          mkdir artefatos
          echo "Arquivo de artefato 01" > ./artefatos/primeiro_arquivo.txt
          echo "Arquivo de artefato 02" > ./artefatos/segundo_arquivo.txt
          echo "Arquivo de artefato 03" > ./artefatos/terceiro_arquivo.txt
          echo "Arquivo de artefato 04" > ./artefatos/quarto_arquivo.txt

      - name: Envio dos arquivos como artefato
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: ${{ env.nome_artefato }}
          path: ./artefatos

      - name: Verificação de arquivos enviados
        run: ls ./artefatos

      - name: Mensagem final
        run: |
            echo "Artefatos enviados com sucesso: ${{ env.nome_artefato }}"